apiVersion: v1
kind: Service
metadata:
  name: {{.Values.global.helloCammis.name}}-service
  labels:
    app: {{.Values.global.helloCammis.name}}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.global.helloCammis.servicePort }}
      targetPort: {{ .Values.global.helloCammis.containerPort }}
      protocol: TCP
  selector:
    app: {{.Values.global.helloCammis.name}}
