global:
    helloCammis:
        containerPort: 3000
        servicePort: 3000
        name: hello-cammis
        imageName: 166636506311.dkr.ecr.us-west-2.amazonaws.com/hello-cammis
        # imageVersion: 0.0.0 # This can be use via command line `--set global.helloCammisq.imageVersion=0.0.0`, otherwise default is `version-{{ .Chart.Version }}`

tags:
    # Prevents transitive deps from deploying
    localDev: false 
    