global:
    helloCammis:
        containerPort: 3000
        servicePort: 3000
        name: hello-cammis
        imageName: cadhcscammis/hello-cammis
        imageVersion: 2.0.17 # Overwrite this with tag when scripting

tags:
    # Prevents transitive deps from deploying
    localDev: false 
    