version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.2.1
        environment:
          NODE_ENV: test
    steps:
      - checkout
      - run:
          name: Update conatiner repositories
          command: sudo apt-get update
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test
      # - run:
      #     name: Install codeclimate reporter module
      #     command: sudo npm install -g codeclimate-test-reporter
      # - run:
      #     name: Send test coverage stats to code climate
      #     command: codeclimate-test-reporter < coverage/lcov.info
      - run:
          name: If pull-request, trigger a review build
          command: |
            if [ $CIRCLE_PULL_REQUEST ] ; then
              echo Calling build job for PR: $CIRCLE_PULL_REQUEST
              echo Git SHA1 to build: $CIRCLE_SHA1
              GIT_PR_NUM=${CIRCLE_PULL_REQUEST##*/}
              REVIEW_ENV_NAME="review_${CIRCLE_BRANCH}_pr${GIT_PR_NUM}"
              # Trigger "build" job in this CircleCI config with review env name
              CCI_API_URL="https://circleci.com/api/v1.1/project/github/ca-mmis"
              # Generate JSON doc with build parameters
              CCI_PARAMS="{\"build_parameters\":{\"CIRCLE_JOB\":\"build\", \
                \"REVIEW_ENV_NAME\":\"${REVIEW_ENV_NAME}\"}}"
              curl -u ${CIRCLE_API_KEY}: -X POST \
                --header "Content-Type: application/json" \
                -d "${CCI_PARAMS}" \
                ${CCI_API_URL}/${CIRCLE_PROJECT_REPONAME}/tree/${CIRCLE_BRANCH}
            fi
      - persist_to_workspace:
          root: ~/repo
          paths: .
  # This will build a Docker image and push it to an ECR
  # Triggered by tagging the repo in GitHub, or via CircleCI API for PRs
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build and push application Docker image
          command: |
            echo "Git SHA1: ${CIRCLE_SHA1}"
            echo "Git Branch: ${CIRCLE_BRANCH}"
            echo "Git Tag: ${CIRCLE_TAG}"
            echo "Review Env: ${REVIEW_ENV_NAME}"
            if [ "${REVIEW_ENV_NAME}" ]; then 
              IMAGE_TAG="${REVIEW_ENV_NAME}"
            elif [ "${CIRCLE_TAG}" ]; then
              IMAGE_TAG="${CIRCLE_TAG}"
            else
              echo "No Docker image tag!"
            fi
            if [ "${IMAGE_TAG}" ]; then
              docker build -t ${AWS_ECR_REPO_NAME}:${IMAGE_TAG} \
                -t ${AWS_ECR_REPO_NAME}:commit-${CIRCLE_SHA1} .
              login="$(aws ecr get-login --region $AWS_DEFAULT_REGION)"
              ${login}
              docker push ${AWS_ECR_REPO_NAME}:${IMAGE_TAG}
              docker push ${AWS_ECR_REPO_NAME}:commit-${CIRCLE_SHA1}
            fi

# This will run the "test" job on any git-push, but the "build" job only on a tag push
# The "test" job will also spawn a build job if there's a Pull-Request defined
# For a tag push, the branch info is empty.
# The "tags" filter in the "test" job is necessary for the "build" job to run.
workflows:
  version: 2
  test-build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
